# Theme
remote_theme: pages-themes/minima@v0.2.0
plugins:
  - jekyll-remote-theme

# Basics
title: Carl Cervone
description: Carl Cervone's personal page
avatar: "/assets/img/avatar-icon.png"

# Nav bar
nav_links:
  - title: Home
    url: /
  - title: About
    url: /carl
  - title: Twitter
    url: https://twitter.com/carl_cervone
  - title: GitHub
    url: https://github.com/ccerv1
  - title: Mirror
    url: https://mirror.xyz/cerv1.eth
  - title: LinkedIn
    url: https://www.linkedin.com/in/carlcervone

# Footer
footer_links:
  - title: GitHub
    url: https://github.com/ccerv1
  - title: Twitter
    url: https://twitter.com/carl_cervone
