# Theme
remote_theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Basics
title: Carl Cervone
description: Founder and data scientist helping organizations make smarter funding decisions for the public good
